# Generated by Django 4.1.7 on 2023-03-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyect",
            name="image",
            field=models.ImageField(upload_to="portfolio/image"),
        ),
    ]
